/*describe('17.12.2024', () => {
  it('Test tooltip ', () => {
    cy.viewport(1440, 1200)
    cy.visit('https://atp.metis.academy')
    cy.contains('Popover&tooltip').click()
    cy.contains('Tooltip').click()
    cy.get('h1').contains('Tooltip').parent().find('.tooltip-item').trigger('mouseover')

    cy.wait(2000)

    cy.get('h1').contains('Tooltip').parent().find('.tooltip-item').trigger('mouseout')

    cy.wait(2000)
  })
})*/

describe('20.12.2024', () => {
  it('Test tooltips ', () => {
    cy.viewport(1440, 1200)
    cy.visit('https://atp.metis.academy')
    cy.contains('Popover&tooltip').click()
    cy.contains('Tooltip').click()
    cy.get('h1').contains('Tooltips').parent().find('.tooltip-item').eq(0).trigger('mouseover')
    .parent()
    .next()
    .trigger('mouseover')
    .next()
    .trigger('mouseover')
    .next()
    .trigger('mouseover')
    .next()
    .trigger('mouseover')
    .next()
    .trigger('mouseover')
    .next()
    .trigger('mouseover')
    .next()
    .trigger('mouseover')
    .next()
    .trigger('mouseover')
    .next()
    .trigger('mouseover')
    .trigger('mouseout')
    .prev()
    .trigger('mouseout')
    .prev()
    .trigger('mouseout')
    .prev()
    .trigger('mouseout')
    .prev()
    .trigger('mouseout')
    .prev()
    .trigger('mouseout')
    .prev()
    .trigger('mouseout')
    .prev()
    .trigger('mouseout')
    .prev()
    .trigger('mouseout')
    .prev()
    .trigger('mouseout')
    .prev()

    cy.go('back')
  })
})
